#!/usr/bin/env node
const { spawnSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const config = require('../src/config/config');
const home = path.resolve(config.forge.minecraftHome);
const version = config.minecraft.version;
const metadata = path.join(home, 'versions', version, `${version}.json`);
const clientJar = path.join(home, 'versions', version, `${version}.jar`);
const mods = path.resolve(config.forge.modDirectory);
const jars = fs.existsSync(mods) ? fs.readdirSync(mods).filter((name) => name.endsWith('.jar')).sort() : [];
const java = spawnSync(config.forge.javaPath, ['-version'], { encoding: 'utf8' });
const available = (name) => { try { require.resolve(name); return true; } catch { return false; } };
console.log(`Node: OK (${process.version})`);
console.log(`Java: ${java.status === 0 ? (java.stderr || java.stdout).trim().split('\n')[0] : 'JAVA_RUNTIME_MISSING'}`);
console.log(`Minecraft client: ${fs.existsSync(metadata) && fs.existsSync(clientJar) && fs.existsSync(path.join(home, 'libraries')) && fs.existsSync(path.join(home, 'assets', 'objects')) ? 'OK' : 'MISSING'}`);
console.log(`Minecraft version: ${config.minecraft.version}`);
console.log(`Forge: ${fs.existsSync(config.forge.forgeHome) ? 'present' : 'MISSING'}`);
console.log(`Forge version: ${config.forge.forgeVersion || 'NOT_CONFIGURED'}`);
console.log(`Mods directory: ${mods} (${fs.existsSync(mods) ? 'present' : 'missing'})`);
console.log(`Loaded mods (${jars.length}): ${jars.join(', ') || 'none'}`);
console.log(`Canvas: ${available('canvas') ? 'OK' : 'MISSING'}`);
console.log(`Prismarine Viewer: ${available('prismarine-viewer') ? 'OK' : 'MISSING'}`);
console.log(`Dashboard port: ${config.web.port}`);
console.log(`Viewer port: ${config.viewer.port}`);
console.log(`Forge client command: ${config.forge.clientCommand}`);
console.log(`Server configuration status: host=${config.minecraft.host ? 'configured' : 'missing'}, port=${config.minecraft.port ? 'configured' : 'missing'}, loader=${config.minecraft.loader}`);
